FROM node:20-slim

# OpenSSLはPrismaの動作に必要
RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npx prisma generate

EXPOSE 3001

# 開発用のtsxで起動
CMD ["npm", "run", "dev"]